(function() {var implementors = {};
implementors['minwin'] = ["impl&lt;T: <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/any/trait.Any.html' title='core::any::Any'>Any</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='minwin/named/enum.CreateNamedError.html' title='minwin::named::CreateNamedError'>CreateNamedError</a>&lt;T&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='minwin/string/struct.NulError.html' title='minwin::string::NulError'>NulError</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='minwin/sync/enum.LockError.html' title='minwin::sync::LockError'>LockError</a>&lt;'a&gt;","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='minwin/sync/enum.TryLockError.html' title='minwin::sync::TryLockError'>TryLockError</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='minwin/sync/enum.TryAcquireError.html' title='minwin::sync::TryAcquireError'>TryAcquireError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='minwin/waitable/enum.WaitError.html' title='minwin::waitable::WaitError'>WaitError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
